### ISSUE TITLE
Multi statement support

### ISSUE THREAD

**Issue by paarthmadan** [github/trilogy#34]
#### Feature Request: Adding support for multi statement

At Shopify, we're exploring the work required to migrate to using the Trilogy client (and respective Active Record adapter). One pre-requisite for adoption is support for multi statement queries.

We enable[ `Mysql2::Client::MULTI_STATEMENTS` ](https://github.com/brianmario/mysql2#multiple-result-sets)(the equivalent to [`TRILOGY_CAPABILITIES_MULTI_STATEMENTS`](https://github.com/github/trilogy/blob/c9eb4e43e8c7371dbf07731fe07c4d44d95817b0/inc/trilogy/protocol.h#L123)) to enable some specific performance optimizations and are interested in seeing this supported in Trilogy. 

#### Discussion
It seems there's already interest, as I was happy to [stumble on this existing branch](https://github.com/github/trilogy/compare/main...multiple-statements) by @composerinteralia and @jhawthorn which seems to prototype some of this work. 

I'm curious to understand what your thoughts are on bringing support for this. I'd love for this issue to be a place to exchange perhaps already existing context like:

1. Are you willing to accept this feature into Trilogy
1. Are there any particular blockers you've discovered? 
1. Any particular API decisions you have considered?
  a. Any thoughts on mimicking `mysql2`'s Ruby API: [`client.next_result` and `client.store_result`](https://github.com/brianmario/mysql2#multiple-result-sets)
  b. Should multi statement be something the C library is aware of, or could this be a Ruby-binding-only abstraction

#### Moving forward

I'd like to note that I'm happy to build this feature out and was intending to draft out some work I have locally. I noticed your branch and figured it would be best to first solicit early feedback and share any context before presenting a solution.

Curious to hear your thoughts and context!

cc: @adrianna-chang-shopify @casperisfine

**Comment by brianmario** [comment]
Not that it was requested (😇), but here's my own input on this:

IMHO I think this should be something that is exposed on the higher level bindings only. The C API is (or at least was) designed to be intentionally lower-level - a lot closer to the protocol - so that other bindings could be built on top in a more flexible way. The C API also intentionally doesn't perform any buffering (outside of a single packet). So anything beyond that is also up to the higher level bindings to handle (like [buffering the resultset before returning to the caller](https://github.com/github/trilogy/blob/main/contrib/ruby/ext/trilogy-ruby/cext.c#L681-L710)). So doing something akin to libmysqlclient's `store_result` down in the C API feels wrong (to me). With my current understanding of the protocol, our C API already exposes everything we'd need to build this into higher level bindings (Ruby being the only one included in this repo).

Adding something like `Trilogy#next_result` seems like it could be made pretty clean 👍. Some of the internals of `execute_read_query` could probably be split out into that and then reused there as well?
